In [9]:
# for test

from rdkit import Chem
from rdkit import DataStructs
smis = [
    'CO[C@H]1\C=C\O[C@@]2(C)OC3=C(C)C(O)=C4C(O)=C(NC(=O)\C(C)=C/C=C/[C@H](C)[C@H](O)[C@@H](C)[C@@H](O)[C@@H](C)[C@H](OC(C)=O)[C@@H]1C)C1=C(N=C5C=C(C)C=CN15)C4=C3C2=O',
    'CN(CCOC1=CC=C(CC2SC(=O)NC2=O)C=C1)C1=CC=CC=N1'
]
mols = []
for smi in smis:
    m = Chem.MolFromSmiles(smi)
    mols.append(m)


fps = [Chem.RDKFingerprint(x) for x in mols]
sm01 = DataStructs.FingerprintSimilarity(fps[0], fps[1])

print("similarity between mol1 and mol2: %.2f" %
      sm01)  # similarity between mol1 and mol2: 0.93

similarity between mol1 and mol2: 0.33


In [1]:
# generate matrix of tanimoto coefficient

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit import DataStructs

datas = pd.read_excel("SMILES_test.xlsx")

x = np.zeros((datas.shape[0],datas.shape[0]))

smis = datas["SMILES"]

mols = []
for smi in smis:
    m = Chem.MolFromSmiles(smi)
    mols.append(m)

fps = [Chem.RDKFingerprint(i) for i in mols]

for i in range(len(fps)):
    for j in range(len(fps)):
        x[i][j] = DataStructs.FingerprintSimilarity(fps[i], fps[j])
        j += 1
    i += 1

print(x)

[[1.         0.04365079 0.04779412 ... 0.08237232 0.08558559 0.08643933]
 [0.04365079 1.         0.84172662 ... 0.08438819 0.20277296 0.09558824]
 [0.04779412 0.84172662 1.         ... 0.09189641 0.20336134 0.10903173]
 ...
 [0.08237232 0.08438819 0.09189641 ... 1.         0.3071161  0.44096386]
 [0.08558559 0.20277296 0.20336134 ... 0.3071161  1.         0.30981818]
 [0.08643933 0.09558824 0.10903173 ... 0.44096386 0.30981818 1.        ]]


In [6]:
# save the matrix

df = pd.DataFrame(x)
SMIS = pd.ExcelWriter('my.xlsx')
df.to_excel(SMIS)
SMIS.save()

In [3]:
from scipy.cluster import hierarchy
linked_array = hierarchy.ward(x)
hierarchy.dendrogram(linked_array)
ax = plt.gca()
bounds = ax.get_xbound()
ax.plot(bounds, [34.5,34.5], '--', c='gray')
ax.plot(bounds, [55,55], '--', c='gray')
ax.text(bounds[1], 55, ' 3 clusters', va='center')
ax.text(bounds[1], 34.5, ' 6 clusters')
plt.xlabel('Compounds', fontsize=12)
plt.xticks([])
plt.ylabel('Cluster distance', fontsize=12)
plt.title('Dendrogram for Ward method', fontsize=14)

ModuleNotFoundError: No module named 'scipy'

In [4]:
from scipy.cluster import hierarchy

ModuleNotFoundError: No module named 'scipy'